# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin@admin.com:
                        password: $2y$12$MBdb0F8O2t4PdcZL5R52Y.hCuYXB1EABw6MHQ8xuBdEBVidgyOkcS
                        roles: 'ROLE_ADMIN'
                    user@user.com:
                        password: $2y$12$xNp2MvonbR1oKjuzJItIi.gNnvclOLg1v/2tfYJ.GhlkZflsZ5UDm
                        roles: 'ROLE_USER'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

    access_control:
#        - { path: ^/protected, roles: IS_AUTHENTICATED_FULLY }
#        - { path: ^/product, roles: ROLE_USER }
